version: '3'
services:
    profile-service:
      build:
        context: .
        args:
          version: 0.0.1
        dockerfile: Dockerfile
      depends_on:
        - redis-server
        - mongodb-server
      ports:
        - "8080:8080"
      networks:
        - spring-boot-profile-network
      links:
        - redis-server
        - mongodb-server
        - zookeeper
        - kafka
  redis-server:
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    hostname: redis-server
    ports:
      - "6379:6379"
    networks:
      - spring-boot-profile-network
  mongodb-server:
    image: mongo
    restart: always
    hostname: localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - spring-boot-profile-network
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - spring-boot-profile-network
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - spring-boot-profile-network

networks:
  spring-boot-profile-network:
    driver: bridge