sbr:
  service:
    kafka-config:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      topic: profile_events
      group-id: events-group
    mongodb: # MongoDB configuration
      config:
        #        Indexed(expireAfter = "10s") String expireAfterTenSeconds;
        #        Indexed(expireAfter = "1d") String expireAfterOneDay;
        #        Indexed(expireAfter = "P2D") String expireAfterTwoDays;
        retention-time: 10s
        primary:
          host: localhost
          port: 27017
          database: primary-profiles-collections
          authentication-database: admin
          username: admin
          password: changeit
          repositories:
            enable: true
        secondary:
          host: localhost
          port: 27017
          database: secondary-profiles-collections
          authentication-database: admin
          username: admin
          password: changeit
          repositories:
            enable: true
    rediscache: # Redis Configuration
      config:
        hostName: redis-server
        port: 6379